name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deploy
        environment:
          name: github-pages
